### ISSUE TITLE
Adding Filter by Nature, and Growth

### ISSUE THREAD

**Issue by DreamerAI** [Lileep/PixelmonDetector#1]
Perfect working detector, but sadly, there is no enough filter for full gameplay. It'd be great if you add some functions like filter Nature,Growth e.t.c

**Comment by Lileep** [comment]
Hi, thanks for replying! Unfortunately, critical details like ivs, natures and growths are hidden in net packets by Pixelmon in recent versions, for security data transmission. This operation keeps clients away from server data unless using packets to access.

In a word, 
- If I simply add nature and growth filters without net packets applied like how previous works do, it'll give u fake infos when u're playing in servers, i.e. show u a wrong nature or growth of a pokemon;
- If I add those filters with net packets functions, it'll greatly decreases the performance of this mod, since it may need to send those packets every tick (about 1/20 second) in order to get those infos refreshed, and it may even trigger alerts of server network detection related plugins.

That's the reason why some previous radar modder also avoid to add ivs, natures and growths filters after Pixelmon 7.x, so those filters might NEVER be added in future. However, you can just open `allowRightClickInfo` in config file, write the pokemons in the filter blank, then right click pokemons u wish to track with empty hands to expose their info like how Ras's lens do, this function can provide u all critical details of pokemons.

**Comment by Lileep** [comment]
Additionally, the filters u mentioned can work only in client, so if u wish to use those filters only in client, then I can try to create a client-oriented detector to add those filters and even more functions that rely on network packets like Pokedex filling tracking for u. :)

**Comment by DreamerAI** [comment]
I got it. Thanks for your answers. It was really interesting to know. Unfortunately, **allowRightClickInfo** don't work on servers.

**Comment by Lileep** [comment]
> I got it. Thanks for your answers. It was really interesting to know. Unfortunately, **allowRightClickInfo** don't work on servers.
> 
> You made really great job!

Ok, np. :)

That config is a bit harmful to servers, so I chose to make it depend on server config.

Have fun playing!
