### ISSUE TITLE
Community Server

### ISSUE THREAD

**Issue by wastedgaming** [Lileep/PixelmonDetector#13]
Can we get a discord server that we could use for suggestions and questions that can be easily answered by the community and what not? also is there anyway to search for pokemon that have a hidden ability? ex: ab:HA and it shows all pokemon with a HA?

**Comment by Lileep** [comment]
Thx for ur reply!
As I'm kinda busy, I can't spare time to manage a community discord server, sry for that. If there're some problems, u can either open a new issue, send me an email or just add my discord. Moreover, if players are willing to create one discord server, feel free to let me in. :D
For hidden abilities searching, the problem is that clients don't know the true ability of pokemons while playing in servers. To solve this, network interactions might be required, but I don't recommend to do so. See [Issue 1](https://github.com/Lileep/PixelmonDetector/issues/1) for more info.

**Comment by DarkVillager** [comment]
@Lileep @wastedgaming I'd be up to moderate/create a pixelmonDetector community server.

**Comment by Lileep** [comment]
> @Lileep @wastedgaming I'd be up to moderate/create a pixelmonDetector community server.

Great! My discord is lileep#9343, u can add me and drag me to the server.

**Comment by DarkVillager** [comment]
> 

Request send (Dark_Ville#2756)

**Comment by Lileep** [comment]
Done. Click [here](https://discord.gg/kmmUKKSx9V) to join!
