### ISSUE TITLE
Legendaries not marked

### ISSUE THREAD

**Issue by loweluis** [Lileep/PixelmonDetector#18]
Some legendaries are not marked and they also don't have lines pointing to them. Any fixes?

**Comment by Lileep** [comment]
Hi there, thx for ur reply!

I noticed that new paradox legendaries like Walking Wake and Iron Leaves were not considered as legendaries in game. U may found that Walking Wake and Iron Leaves spawn as normal pokemons instead of legendaries in latest reforged (9.1.7), that's the main reason. It's mainly caused by reforged itself, those 2 haven't been added to legendary list yet. Detector use the legendary list provided by reforged, so it doesn't consider them as legendaries, either.

I recommend u to wait for the updating of reforged. Once they add those 2 to legendary list, the Detector would work well again. Manually adding them to Detector legendary list is kinda...redundant, since I may need to remove them after they are added to the reforged legendary list in future versions. So for now, u can use the search function as an alternative.

**Comment by loweluis** [comment]
Im sorry for the late reply but I'm not talking about the new paradox legendaries, legendaries like shaymin, marshadow and others are not recognized and it doesn't mark them. I didn't change anything with the configs. The photo attached is just an example of marshadow, deoxys, manaphy, magearna not being recognized, I have seen them spawn in the wild before and they didn't have any markers so I made a random legendary spawner to see which ones are not marked.
![image](https://github.com/Lileep/PixelmonDetector/assets/28964712/01d4704c-564a-405c-a2e3-fc107dbb9657)
![image](https://github.com/Lileep/PixelmonDetector/assets/28964712/ae96e128-ddd8-45bb-93cb-558d34f65457)
![image](https://github.com/Lileep/PixelmonDetector/assets/28964712/0a0c0b15-11d0-406d-b55f-b105bd8b44fa)

**Comment by loweluis** [comment]
![image](https://github.com/Lileep/PixelmonDetector/assets/28964712/c255160f-7871-4ee9-ac20-73278795f624)
![image](https://github.com/Lileep/PixelmonDetector/assets/28964712/a92091b7-aaee-470c-98ad-5b9a4e380a93)
More photos of them not getting marked

**Comment by Lileep** [comment]
> ![image](https://user-images.githubusercontent.com/28964712/266828943-a92091b7-aaee-470c-98ad-5b9a4e380a93.png) More photos of them not getting marked

Confirmed. I just noticed that reforged don't consider mythical pokemons like Mew and Marshadow as normal legendaries(LOL), I should add them separately. Thx for ur report!

**Comment by Lileep** [comment]
Solve. Try 1.3! XD
