### ISSUE TITLE
searching for abilities doinst work in 1.16.5

### ISSUE THREAD

**Issue by michelangelo02** [Lileep/PixelmonDetector#23]
hello it doinst work when searching for abilities, idunno if its just me but when i search after a specifik ability it wont show even if i spawned the poke with the specifik ability i need /pokespawn gible ability:RoughSkin it doinst show when i do the following ab:RoughSkin and i have tried a:roughskin, abl:roughskin and even tried with other abilities such as trace and even steamengine the example you chose.

**Comment by Lileep** [comment]
Hi, thx for ur reply!
Ability searching works only when the `allowPokemonKeyInfo` config is set to true due to the information transmitting consideration (Reasons in details can be find in [Issue 1](https://github.com/Lileep/PixelmonDetector/issues/1)). See [here](https://github.com/Lileep/PixelmonDetector/wiki/Configs#allowpokemonkeyinfo-boolean) to get more info. Feel free to reply if u have any other doubts :)

**Comment by Lileep** [comment]
So it's been about 3 weeks, how's this issue going? If there's no other problem, I'll close this issue

**Comment by Lileep** [comment]
It’s been a month and I'd close it. If there're any questions, pls ask again
