### ISSUE TITLE
Partially stopped working?

### ISSUE THREAD

**Issue by Pokehunter007** [Lileep/PixelmonDetector#25]
I have been playing in this server siyntra studios which has 9.1.1  .
For first few days everything was working fine but on 3 rd day...half the function stopped working  
Stopped features - Spotting pokeloots , Spotting Shiny and legendaries, Spotting bosses 
Still working features -  Ultra portal spotting, Search Spotting only

What to do.?

**Comment by Lileep** [comment]
Hi, thx for ur reply!
This might be because the server u are playing on also has Pixelmon Detector installed and applies some restrictions on it through the config. Because Pixelmon Detector will first try to read and load the server config, and will only read the client config if Detector is not installed on the server. This ensures that the server admins can restrict player behaviors through config and ensure the playability of the server. For details, please view the [home page of this repo](https://github.com/Lileep/PixelmonDetector?tab=readme-ov-file#features) and wiki's config section of this project.
If u're sure that the server u're playing on doesn't have Pixelmon Detector installed, then feel free to continue to reply!

**Comment by Pokehunter007** [comment]
As a new in these things , I am not sure if it's installed in the server or not but if not much , can u please join for a minute and check it ? It would be if hugge help
 Thank you 
Ip: mc.siyntrastudios.com

**Comment by Lileep** [comment]
> As a new in these things , I am not sure if it's installed in the server or not but if not much , can u please join for a minute and check it ? It would be if hugge help Thank you Ip: mc.siyntrastudios.com

Unfortunately, I'm not able to get mod installation details on a specific server as well. This is probably only known by the server admins. So it is better to ask them. In addition, even if they didn't install Pixelmon Detector, they may use other methods (such as anti-cheat plugins or mods) to restrict this mod. Hope that u can understand.
