### ISSUE TITLE
Ability to Export pokedex completion

### ISSUE THREAD

**Issue by DarkVillager** [Lileep/PixelmonDetector#9]
To csv or xlsx somehow?

**Comment by Lileep** [comment]
Well, that's indeed not a bad idea, those data can be export to some where like the saves/world folder, and u can clearly figure out which mons are not yet in ur dex.
However, as far as I'm concerned, it's...umm, I don't think this feature should appear in a small detector mod. This mod is focused on tracking after all. You can just simply figure out those mons that haven't been caught in ur pokedex and use the searching gui to search them.
The export function should more likely be in a dex helper server plugin since it mainly interact with server data and the dex info need to be updated frequently. So I guess a customized plugins can help u with this pokedex completion function. If this detector is going to equip such function, I'll reopen this issue in future. Ty!
